### ISSUE TITLE
Plugin does not offer MIN_MAX values in performance data (no perf data at all)

### ISSUE THREAD

**Issue by ronator** [egnite/querxnagios#1]
Hi,

I am starting to monitor a "Querx TH". I used egnite's tutorial but with icinga2 I prefer to use "apply for ... in" and host templates. The check works fine, but there are some things that confuse me because I feel fooled by egnite:

1) The plugin **does not create a complete performance data string**; this happens on console and with the web UI. Even when I set WARN and CRIT to some range values, all I get is (with --verbose!)

WARNING: [TEST-SENSOR:Temperature] 26.50 °C | Temperature=26.5;;;;

This is confusing me, because the screenshots from here

http://sensors.egnite.de/wp-content/uploads/sites/4/2016/06/icinga2_kritischer_status.png

**will let you assume, that it does show warn and crit values in the output on both console and web ui** because this is how it works - but since even the MIN and MAX values in the picture of the tutorial are wrong (MAX = 20, MIN = 25 ???) I ssume this image **must be a fake**.

Since the Go binary can't be read I checked the code here - I cannot find any place in the code where it creates a complete performance data string. So what you show on your website in your tutorial is - nicely said - not true.

This also means, any trending data like "pnp4nagios" will not show the WARN or CRIT limit line (the yellow and the red line) in the graph.

2) The Plugin does not support any serious auth method
If you define a user account and a password, the plugin can't work - are you kidding me?

So my main questions are
_- Please enlighten me how you get the CRIT/WARN or MIN/MAX values in the performance data output as shown in your icingaweb2 image._ (In the tutorial, the console output also doesn't show full perf data.)

_- Why is there no switch --user / --password for the plugin so that you can define a user with password?_ 

I am considering to send the sensor back, because this is really annoying - I **consider myself to be mislead by egnite's false tutorial** and this half-done plugin.

**Comment by ronator** [comment]
Aaah, line 72 says: //If started with --auth  we also need a username and a password

and 15 to 18

//TLS             *bool
//Auth            *bool
//Username        *string
//Password        *string

####

$ /usr/lib/nagios/plugins/check_querx --help

Usage: check_querx [-hvV] [-c value] [-H value] [-P value] [-s value] [-w value] [parameters ...]
 -c, --critical=value
 -h, --help        Print help screen
 -H, --hostname=value
                   Hostname
 -P, --port=value  HTTP Port
 -s, --sensor=value
                   Sensor ID
 -v, --verbose     1
 -V, --version     Print version
 -w, --warning=value

What --auth? So I guess this will come soon?

**Comment by egnite** [comment]
Hi,

On 06.06.2017 16:19, ronator wrote:
> What --auth? So I guess this will come soon?

I'm not the author and I'm not a Go programmer. If you look further
down, there are more commented lines regarding authentication. However,
not sure, why the author disabled these lines.

Btw. if not 100% satisfied with your Querx, you will probably get a
refund from egnite.

Best regards,

Harald

**Comment by ronator** [comment]
Thank you for your quick answer.

I am sorry if I got "a bit emotional" on the subject, because the documentation on egnite's website seems quite off (reality). Since we bought it as a company, I am not sure if we can refund it, but anyway, thank you for your straight answer.

I guess, we all can only assume why there are these out-commented lines of code - my best guess after 'reading' the code would be that  authentication was a targeted feature but the applications simply seems to lack needed libraries and functions to authenticate over http/s.

But this is just a challenge, not a problem at all since we are on github here and your account seems to be affiliated to egnite so it would be in egnite's very interest to fullfil your customer's needs to improve this plugin so that it somewhat complies to "nagios plugin developer guidelines" regarding performance data output.

I don't know anything 'Go' - I heard it's great though for certain tasks - but maybe we could find some guys/girls who could help us out. I understand you are the maintainer of this code but you don't speak Go, either?

I think I could provide the needed Go code to have the plugin output correct nagios performance data because this is just a matter of "echo'ing some variables" in the exit code, so this seems easy to me. But I can't cover authentication (yet).

If you are actually affiliated with egnite, I would consider it very cool if your company would spend some ressources on the "lack of features" of this go binary because it really affects customers:

- you don't have MIN:MAX limit lines in your long term trending data (pnp4nagios, prometheus)
- you can't secure sensors web ui by authentication because the plugin will then fail

These issues are quite annoying for every serious and/or professional administrator, especially in companies. **Considering the fact that the product is sold with detailed information on how to use it with icinga(web)2 _while the plugin's monitoring functionality just doesn't support these basic topics_** is really dissatisfying.

Best,
Ron

**Comment by ronator** [comment]
The code also relies on https://github.com/olorin/nagiosplugin so this should be kept in mind in terms of compatibility of all packages.

This is the part that we need to use/improve:

```go
// Add some perfdata too (label, unit, value, min, max,
// warn, crit). The math.Inf(1) will be parsed as 'no
// maximum'.
check.AddPerfDatum("badness", "kb", 3.14159, 0.0, math.Inf(1), 8000.0, 9000.0)
```

**Comment by ronator** [comment]
Ok, from what I figured out by now we need to change lines 70 and 73 of check_querx.go to output at least min:max values in perf data. This should not be crucial, since we are just adding variables wLower/wUpper and cLower/cUpper to the output messages in the respective lines.

Would you be able to merge a pull request considering this feature request? I already forked your repo but I don't have a Go environment available yet and I want to test it locally for sure and I would like you to also acknowledge this patch.

Best

**Comment by ronator** [comment]
Ok, I got so far already, but this will ONLY cover the UPPER warn and critical - the LOWER warn and critical can't be covered due to issue with nagiosplugin.go.

So when I have icinga call the improved plugin with
check_querx -H 10.10.10.10 -s 0 -v -w 26 -c 28
icingaweb2 displays this:

![auswahl_567](https://user-images.githubusercontent.com/6568335/26930884-08840d36-4c5f-11e7-97e1-25a64d66b43c.png)

Still not perfect but better. I will now check if it draws the limit lines correctly in pnp4nagios.

I added the compiled go binary to my repo, feel free to download and execute it.

**Comment by ronator** [comment]
fun fact: https://github.com/egnite/querx

**Comment by ronator** [comment]
This looks so much better:
![auswahl_594](https://user-images.githubusercontent.com/6568335/27485350-b10e8b9c-582c-11e7-8171-f292f7b278a1.png)

There is still an issue with icingaweb2 itself, but the plugin does its job correctly. Thank you very much for your effort.
